### ISSUE TITLE
Design on-boarding screens

### ISSUE THREAD

**Issue by andresousa** [scannieapp/scannie-ios#7]

**Comment by alvesjtiago** [comment]
What should we include in the on boarding process? Will it display before or after the login via Blockstack?

My suggestion would be to have 3 screens displayed before the login process with:
1. Capture your documents (intuitive scanning)
2. Stored safely (talk about encryption and accessibility)
3. How does it work (describe Blockstack login process with CTA to start now)

cc @andresousa

**Comment by andresousa** [comment]
Sounds perfect!
3 screens before login with those topics.

**Comment by alvesjtiago** [comment]
First implementation of the on-boarding screens. Let me know what you think @andresousa.

<img width="966" alt="Screenshot 2019-04-21 at 21 27 03" src="https://user-images.githubusercontent.com/407470/56475173-aa749480-647c-11e9-9726-1f15972003bd.png">

**Comment by andresousa** [comment]
Looks great!
It's just missing the dot page indicators on the bottom of the screens, but I will use the iOS native components, so we're good!
